version: '3.8'

services:
  # BioCypher pipeline service
  {{ cookiecutter.package_name }}:
    build: .
    container_name: {{ cookiecutter.package_name }}-pipeline
    volumes:
      - ./data:/app/data:ro
      - ./logs:/app/logs
      - ./output:/app/output
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=password
    depends_on:
      - neo4j
    networks:
      - biocypher-network

  # Neo4j database service
  neo4j:
    image: neo4j:5.15-community
    container_name: {{ cookiecutter.package_name }}-neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/password
      - NEO4J_PLUGINS=["apoc"]
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_import:/var/lib/neo4j/import
      - neo4j_plugins:/plugins
    networks:
      - biocypher-network

volumes:
  neo4j_data:
  neo4j_logs:
  neo4j_import:
  neo4j_plugins:

networks:
  biocypher-network:
    driver: bridge
